#!/usr/bin/env sh

. "$(dirname "$0")/libs/common.sh"
common_libs

. "$(dirname "$0")/libs/commit_rules.sh"
. "$(dirname "$0")/libs/tag_process.sh"
. "$(dirname "$0")/libs/changelog.sh"

#Hook start here

# metadata dedicated
COMMIT_EDITMSG_FILE=$1
COMMIT_EDITMSG=$(cat "$COMMIT_EDITMSG_FILE" 2>/dev/null)

case "$CURRENT_BRANCH" in
HEAD | head | "") ;;
main | origin/main) ;;
develop | origin/develop) ;;
feature/* | origin/feature/*) ;;
bugfix/* | origin/bugfix/*) ;;
hotfix/* | origin/hotfix/*) ;;
release/* | origin/release/*) ;;
*) ;;
esac

commitmsg_guard "$COMMIT_EDITMSG" || exit 1
