#!/usr/bin/env sh

. "$(dirname "$0")/libs/common.sh"
common_libs

. "$(dirname "$0")/libs/commit_rules.sh"
. "$(dirname "$0")/libs/tag_process.sh"
. "$(dirname "$0")/libs/changelog.sh"

#Hook start here

# metadata dedicated
COMMIT_EDITMSG_FILE=$1
COMMIT_EDITMSG=$(cat "$COMMIT_EDITMSG_FILE" 2>/dev/null)

case "$CURRENT_BRANCH" in
HEAD | head | "") ;;
main | origin/main) commitmsg_guard "$COMMIT_EDITMSG" || exit 1 ;;
develop | origin/develop) commitmsg_guard "$COMMIT_EDITMSG" || exit 1 ;;
feature/* | origin/feature/*) commitmsg_guard "$COMMIT_EDITMSG" || exit 1 ;;
bugfix/* | origin/bugfix/*) commitmsg_guard "$COMMIT_EDITMSG" || exit 1 ;;
hotfix/* | origin/hotfix/*) commitmsg_guard "$COMMIT_EDITMSG" || exit 1 ;;
release/* | origin/release/*) commitmsg_guard "$COMMIT_EDITMSG" || exit 1 ;;
*) ;;
esac
