#!/usr/bin/env sh

. "$(dirname "$0")/libs/common.sh"
common_libs

. "$(dirname "$0")/libs/commit_rules.sh"
. "$(dirname "$0")/libs/tag_process.sh"
. "$(dirname "$0")/libs/changelog.sh"

#Hook start here

case "$CURRENT_BRANCH" in
HEAD | head | "") ;;
main | origin/main) ;;
develop | origin/develop) ;;
feature/* | origin/feature/*) ;;
bugfix/* | origin/bugfix/*) ;;
hotfix/* | origin/hotfix/*) ;;
release/* | origin/release/*) ;;
*) ;;
esac
