#!/usr/bin/env sh

. "$(dirname "$0")/libs/common.sh"
common_libs

. "$(dirname "$0")/libs/commit_rules.sh"
. "$(dirname "$0")/libs/tag_process.sh"
. "$(dirname "$0")/libs/changelog.sh"

#Hook start here

CURRENT_COMMIT_MSG="$(cat "$1")"

case "$CURRENT_BRANCH" in
HEAD | head | "") ;;
main | origin/main)
	block_direct_commit "$CURRENT_COMMIT_MSG" || exit 1
	;;
develop | origin/develop)
	block_direct_commit "$CURRENT_COMMIT_MSG" || exit 1
	;;
feature/* | origin/feature/*)
	validate_commit_type "$CURRENT_COMMIT_MSG" "feat docs style refactor perf test chore build ci remove" || exit 1
	;;
bugfix/* | origin/bugfix/*)
	validate_commit_type "$CURRENT_COMMIT_MSG" "fix docs refactor chore revert" || exit 1
	;;
hotfix/* | origin/hotfix/*)
	validate_commit_type "$CURRENT_COMMIT_MSG" "fix docs refactor chore revert" || exit 1
	;;
release/* | origin/release/*)
	validate_commit_type "$CURRENT_COMMIT_MSG" "fix feat docs style refactor perf test chore build ci revert remove" || exit 1
	;;
*) ;;
esac
